apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pioneer-writers
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      # nodePort: XXXX # Automatic k8s assignment
