apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate-job
  namespace: pioneer-writers
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: allanbinga/pioneer-writers-backend:v2.0.1
          command: ["/bin/sh", "-c", "pwd; ls -la /app/prisma; npx prisma migrate deploy"]
          envFrom:
            - secretRef:
                name: db-secret
      restartPolicy: Never
  backoffLimit: 1