name: pioneer-writers

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t allanbinga/pioneer-writers-backend:v2.0.0 .
          docker push allanbinga/pioneer-writers-backend:v2.0.0

      - name: Build and push frontend image
        run: |
          docker build \
            --build-arg VITE_BACKEND_ENDPOINT=http://backend.pioneer-writers.svc.cluster.local:6100/pioneer-writers/v1 \
            --build-arg VITE_GOOGLE_CLIENT_ID=204800037322-e6g2gk84rl3tc1rj899sijsto7r3l9vl.apps.googleusercontent.com \
            -t allanbinga/pioneer-writers-frontend:v2.0.0 ./client
          docker push allanbinga/pioneer-writers-frontend:v2.0.0
